/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ScApp {}
  interface ScAppAttributes extends StencilHTMLAttributes {}

  interface ScBackdrop {}
  interface ScBackdropAttributes extends StencilHTMLAttributes {}

  interface ScCard {
    'heading': string;
  }
  interface ScCardAttributes extends StencilHTMLAttributes {
    'heading'?: string;
  }

  interface ScContainer {}
  interface ScContainerAttributes extends StencilHTMLAttributes {}

  interface ScGrid {}
  interface ScGridAttributes extends StencilHTMLAttributes {}

  interface ScList {}
  interface ScListAttributes extends StencilHTMLAttributes {}

  interface ScNavbar {
    'name': string;
    'toggle': () => void;
  }
  interface ScNavbarAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface ScSection {}
  interface ScSectionAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ScApp': Components.ScApp;
    'ScBackdrop': Components.ScBackdrop;
    'ScCard': Components.ScCard;
    'ScContainer': Components.ScContainer;
    'ScGrid': Components.ScGrid;
    'ScList': Components.ScList;
    'ScNavbar': Components.ScNavbar;
    'ScSection': Components.ScSection;
  }

  interface StencilIntrinsicElements {
    'sc-app': Components.ScAppAttributes;
    'sc-backdrop': Components.ScBackdropAttributes;
    'sc-card': Components.ScCardAttributes;
    'sc-container': Components.ScContainerAttributes;
    'sc-grid': Components.ScGridAttributes;
    'sc-list': Components.ScListAttributes;
    'sc-navbar': Components.ScNavbarAttributes;
    'sc-section': Components.ScSectionAttributes;
  }


  interface HTMLScAppElement extends Components.ScApp, HTMLStencilElement {}
  var HTMLScAppElement: {
    prototype: HTMLScAppElement;
    new (): HTMLScAppElement;
  };

  interface HTMLScBackdropElement extends Components.ScBackdrop, HTMLStencilElement {}
  var HTMLScBackdropElement: {
    prototype: HTMLScBackdropElement;
    new (): HTMLScBackdropElement;
  };

  interface HTMLScCardElement extends Components.ScCard, HTMLStencilElement {}
  var HTMLScCardElement: {
    prototype: HTMLScCardElement;
    new (): HTMLScCardElement;
  };

  interface HTMLScContainerElement extends Components.ScContainer, HTMLStencilElement {}
  var HTMLScContainerElement: {
    prototype: HTMLScContainerElement;
    new (): HTMLScContainerElement;
  };

  interface HTMLScGridElement extends Components.ScGrid, HTMLStencilElement {}
  var HTMLScGridElement: {
    prototype: HTMLScGridElement;
    new (): HTMLScGridElement;
  };

  interface HTMLScListElement extends Components.ScList, HTMLStencilElement {}
  var HTMLScListElement: {
    prototype: HTMLScListElement;
    new (): HTMLScListElement;
  };

  interface HTMLScNavbarElement extends Components.ScNavbar, HTMLStencilElement {}
  var HTMLScNavbarElement: {
    prototype: HTMLScNavbarElement;
    new (): HTMLScNavbarElement;
  };

  interface HTMLScSectionElement extends Components.ScSection, HTMLStencilElement {}
  var HTMLScSectionElement: {
    prototype: HTMLScSectionElement;
    new (): HTMLScSectionElement;
  };

  interface HTMLElementTagNameMap {
    'sc-app': HTMLScAppElement
    'sc-backdrop': HTMLScBackdropElement
    'sc-card': HTMLScCardElement
    'sc-container': HTMLScContainerElement
    'sc-grid': HTMLScGridElement
    'sc-list': HTMLScListElement
    'sc-navbar': HTMLScNavbarElement
    'sc-section': HTMLScSectionElement
  }

  interface ElementTagNameMap {
    'sc-app': HTMLScAppElement;
    'sc-backdrop': HTMLScBackdropElement;
    'sc-card': HTMLScCardElement;
    'sc-container': HTMLScContainerElement;
    'sc-grid': HTMLScGridElement;
    'sc-list': HTMLScListElement;
    'sc-navbar': HTMLScNavbarElement;
    'sc-section': HTMLScSectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
